# serving up the HTTP server
server:
  host: 127.0.0.1
  port: 2222

# create raft node
raft:
  node_id: "node_1"
  host: 127.0.0.1
  port: 1111
  volume_dir: "node_1_data"

#server:
#  host: 127.0.0.1
#  port: 2223
#
## create raft node
#raft:
#  node_id: "node_2"
#  host: 127.0.0.1
#  port: 1112
#  volume_dir: "node_2_data"

#server:
#  host: 127.0.0.1
#  port: 2224
#
## create raft node
#raft:
#  node_id: "node_3"
#  host: 127.0.0.1
#  port: 1113
#  volume_dir: "node_3_data"


